### ISSUE TITLE
SSL certificate is expired

### ISSUE THREAD

**Issue by Chemsmith** [plugorgau/plugorgau.github.io#15]
The SSL certificate for plug.org.au expired in July, I assume this is meant to automatically renew from LE and for some reason hasn't?

**Comment by Chemsmith** [comment]
Scratch that, just realised this is not the repo for THAT plug website!

**Comment by Zorlin** [comment]
No, you're in the right place.

We're aware, but have been swamped. I'm hoping to resolve this tomorrow.

**Comment by Zorlin** [comment]
Hi @Chemsmith - this has now been fixed. Thanks for letting us know :)
