### ISSUE TITLE
What tools should we use?

### ISSUE THREAD

**Issue by luke-john** [plugorgau/plugorgau.github.io#3]
Suggestions
- [Markdown](http://daringfireball.net/projects/markdown/) - text-to-HTML conversion tool
- [Jade](jade-lang.com) - template engine
- [Jekyll](jekyllrb.com) - blog-aware, static site generator in Ruby
- Straight html
- [Twitter Bootstrap](http://getbootstrap.com/) - front-end framework
- [Font Awesome](http://fontawesome.io/) - scalable vector icons

**Comment by Zorlin** [comment]
Markdown + Jekyll in use and in production :)

Please open a new issue or submit a pull request if you find more things we should be using.
